---
title: "Comparacion de métodos para el estudio y monitore de arrecifes coralinos"
author: "Ana M. Palacio-Castro & Fernando A. Zapata"
date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    df_print: paged
    fig_height: 4
    fig_width: 7.5
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
bibliography: packages.bib
nocite: '@*'
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, 
                      options(knitr.kable.NA = '',
                      rows.print=12, digits = 3))
```

# Libraries and settings

```{r}
# Libraries
    library(tidyverse)

#Plots
    library(ggpubr)
    library(ggthemes)
    library(ggplot2)

#Models     
    library(emmeans)
    library(multcomp)

# Plots theme
MyTheme<-theme_bw() +  
theme(legend.position="top",
          plot.background=element_blank(),
          #axis.text.x = element_text(angle = 90, vjust = 0.5),
          axis.title.x=element_blank(),
          axis.text.x=element_blank(),
          axis.ticks.x = element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          legend.box.background = element_rect(),
          #legend.title = element_blank(),
          panel.background =element_rect(fill = NA, 
                                         color = "black"))
```

# Import and format data

```{r}

# 1. Get general cover data
  General.data<-read.csv("Datos/Datos_Categorias_generales.csv", header = T)
  summary(General.data)
  #General.data<-General.data[, (1:14) ]
  Factors<-c("Metodo", "Zona", "Sitio", "Buzo", "Transecto", "Replica")
  General.data<-General.data %>% mutate_at(Factors, factor)

# 2. Riqueza
  Riqueza.data<-read.csv("Datos/Riqueza_Bentos.csv", header = T)
  summary(Riqueza.data)
  Riqueza.data<-Riqueza.data[, -(7:47) ]
  #Factors<-c("Metodo", "Zona", "Sitio", "Buzo", "Transecto", "Replica")
  Riqueza.data<-Riqueza.data %>% mutate_at(Factors, factor)
  
# 3. Time
  Time.data<<-read.csv("Datos/Datos_tiempo.csv", header = T)
  summary(Time.data)
  #Factors<-c("Metodo", "Zona", "Sitio", "Buzo", "Transecto", "Replica")
  Time.data<-Time.data %>% mutate_at(Factors, factor)
  #Time.data <- gather(Time.data, Fase, minutos, Tiempo.Campo..min.:Tiempo.Laboratorio..min., factor_key=TRUE)
  
```

# 1. Coral cover

## Model

```{r}
# Transformacion de los datos
General.data$T_Coral<- asin(sqrt(General.data$Coral/100))

Coral_Cover_model <- lm(T_Coral ~1 +  Metodo + Buzo + 
                          Zona + Sitio%in%Zona + 
                          Metodo*Buzo +
                          Metodo*Zona + Buzo*Zona +
                          Metodo*Buzo*Zona + 
                          Metodo*Sitio%in%Zona +
                          Buzo*Sitio%in%Zona + 
                          Metodo*Buzo*Sitio%in%Zona,
                        data = General.data)

# summary(Coral_Cover_model)                          
  anova(Coral_Cover_model)
  par(mfrow=c(1,2))
  plot(Coral_Cover_model)
  par(mfrow=c(1,1))

  Comp1<-emmeans(Coral_Cover_model, ~Metodo|Zona)
  pairs(Comp1, adj="tukey")
  
  Comp2<-emmeans(Coral_Cover_model, ~Buzo|Metodo)
  pairs(Comp2, adj="tukey")      
```

## Plot

```{r}
Coral_Cover<- ggplot(General.data) + facet_grid(~Transecto)+
  MyTheme+ scale_shape_manual(values=c(21,22,25))+ 
  stat_summary(aes(x=Metodo, y=Coral, fill=Metodo, group=Metodo),
                 fun.data = "mean_cl_boot", geom = "bar", 
                 position=position_dodge(width=0.8), alpha=0.7)+
   stat_summary(aes(x=Metodo, y=Coral, group=Metodo, color=Metodo),
                 fun.data = "mean_cl_boot", geom = "errorbar", 
                 position=position_dodge(width=0.8))+
   geom_point(aes (x=Metodo, y=Coral, shape=Buzo, 
                   fill=Metodo), position = position_dodge(0.8))+
   #geom_jitter( aes (x=Metodo, y=Coral, shape=Buzo, 
  #                   fill=Metodo, group=Metodo))+
    scale_y_continuous(limits = c(0,99),
                      expand = c(0.03, 0.03),
                      breaks = seq(0, 99, 20),
                      name=expression("Cobertura de coral (%)"))
Coral_Cover

Coral_Cover<-Coral_Cover +
    theme(strip.background = element_blank(),
    strip.text.x = element_blank())
```

# 2. Algae cover

## Model

```{r}
General.data$T_Alga<- asin(sqrt((General.data$Alga/100)))

Alga_Cover_model<-lm(T_Alga~ 1 + Metodo + Buzo +
                          Zona + Sitio%in%Zona + 
                          Metodo*Buzo +
                          Metodo*Zona + Buzo*Zona +
                          Metodo*Buzo*Zona + 
                          Metodo*Sitio%in%Zona +
                          Buzo*Sitio%in%Zona + 
                          Metodo*Buzo*Sitio%in%Zona,
                        data = General.data)

  #summary(Alga_Cover_model)                          
  anova(Alga_Cover_model)
  par(mfrow=c(1,2))
  plot(Alga_Cover_model)
  par(mfrow=c(1,1))

  Comp2<-emmeans(Alga_Cover_model, ~Metodo|Zona)
  pairs(Comp2, adj="tukey")
  
  Comp3<-emmeans(Alga_Cover_model, ~Buzo|Metodo)
  pairs(Comp3, adj="tukey")   
  
```

## Plot

```{r}
Algae_Cover<- ggplot(General.data) + facet_grid(~Transecto)+
  MyTheme+ scale_shape_manual(values=c(21,22,25))+ 
  stat_summary(aes(x=Metodo, y=Alga, fill=Metodo),
                 fun.data = "mean_cl_boot", geom = "bar", 
                 position=position_dodge(width=0.8), alpha=0.7)+
  
  stat_summary(aes(x=Metodo, y=Alga, colour=Metodo),
                 fun.data = "mean_cl_boot", geom = "errorbar", 
                 position=position_dodge(width=0.8))+
  geom_point(aes (x=Metodo, y=Alga, shape=Buzo, 
                   fill=Metodo), position = position_dodge(0.5))+
   #geom_jitter( aes (x=Metodo, y=Alga, shape=Buzo, 
  #                   fill=Metodo, group=Metodo))+
  scale_y_continuous(limits = c(0, 90),
                      expand = c(0.03, 0.3),
                      breaks = seq(0, 100, 20),
                      name=expression("Cobertura de algas (%)"))
Algae_Cover
Algae_Cover<- Algae_Cover +
    theme(legend.position="none",
        strip.background = element_blank(),
        strip.text.x = element_blank())

```

# 3. Substrate cover

## Model

```{r}
General.data$T_Sustrato<- acos(General.data$Sustrato /100)

Sus_Cover_model<-lm(T_Sustrato ~  1 + Metodo + Buzo +
                          Zona + Sitio%in%Zona + 
                          Metodo*Buzo +
                          Metodo*Zona + Buzo*Zona +
                          Metodo*Buzo*Zona + 
                          Metodo*Sitio%in%Zona +
                          Buzo*Sitio%in%Zona + 
                          Metodo*Buzo*Sitio%in%Zona,
                        data = General.data)

  #summary(Sus_Cover_model)                          
  anova(Sus_Cover_model)
  par(mfrow=c(1,2))
  plot(Sus_Cover_model)
  par(mfrow=c(1,1))

  Comp5<-emmeans(Sus_Cover_model, ~Metodo|Zona)
  pairs(Comp5, adj="tukey")
  
  Comp6<-emmeans(Sus_Cover_model, ~Buzo|Metodo)
  pairs(Comp6, adj="tukey")   
```

## Plot

```{r}
Substrate_Cover<- ggplot(General.data) + facet_grid(~Transecto)+
  MyTheme+ scale_shape_manual(values=c(21,22,25))+ 
  stat_summary(aes(x=Metodo, y=Sustrato, fill=Metodo),
                 fun.data = "mean_cl_boot", geom = "bar", 
                 position=position_dodge(width=0.8), alpha=0.7)+
  
  stat_summary(aes(x=Metodo, y=Sustrato, colour=Metodo),
                 fun.data = "mean_cl_boot", geom = "errorbar", 
                 position=position_dodge(width=0.8))+
  geom_jitter( aes (x=Metodo, y=Sustrato, shape=Buzo, fill=Metodo, group=Buzo))+
  scale_y_continuous(limits = c(0,80),
                      expand = c(0.03, 0.3),
                      breaks = seq(0, 100, 20),
                      name=expression("Cobertura de sustrato (%)"))
Substrate_Cover
```

# 4. Coral richness

```{r}
hist(Riqueza.data$Riqueza..S.)
```

## Modelo Gaussiano

```{r}

Richness_model<-lm(Riqueza..S. ~  1 + Metodo + Buzo +
                          Zona + Sitio%in%Zona + 
                          Metodo*Buzo +
                          Metodo*Zona + Buzo*Zona +
                          Metodo*Buzo*Zona + 
                          Metodo*Sitio%in%Zona +
                          Buzo*Sitio%in%Zona + 
                          Metodo*Buzo*Sitio%in%Zona,
                          data = Riqueza.data)

 # summary(Richness_model)                          
  anova(Richness_model)
  par(mfrow=c(1,2))
  plot(Richness_model)
  par(mfrow=c(1,1))
  
  Comp7<-emmeans(Richness_model, ~Metodo|Zona)
  pairs(Comp7, adj="tukey")
  
  Comp8<-emmeans(Richness_model, ~Buzo|Metodo)
  pairs(Comp8, adj="tukey")   
  
```

## Modelo Poisson

```{r}
Richness_model_2<-glm(Riqueza..S. ~  1 + Metodo + Buzo +
                          Zona + Sitio%in%Zona + 
                          Metodo*Buzo +
                          Metodo*Zona + Buzo*Zona +
                          Metodo*Buzo*Zona + 
                          Metodo*Sitio%in%Zona +
                          Buzo*Sitio%in%Zona + 
                          Metodo*Buzo*Sitio%in%Zona,
                          data = Riqueza.data, 
                          family = poisson(link = "log"))
  
  
  # summary(Richness_model)                          
  anova(Richness_model_2)
  par(mfrow=c(1,2))
  plot(Richness_model_2)
  par(mfrow=c(1,1))
  
  Comp7<-emmeans(Richness_model_2, ~Metodo|Zona)
  pairs(Comp7, adj="tukey")
  
  Comp8<-emmeans(Richness_model_2, ~Buzo|Metodo)
  pairs(Comp8, adj="tukey")   
```


## Plot

```{r}

Coral_Richness<- ggplot(Riqueza.data) + facet_grid(~Transecto)+
  MyTheme+ scale_shape_manual(values=c(21,22,25))+ 
  stat_summary(aes(x=Metodo, y=Riqueza..S.,
                   fill=Metodo, group=Metodo),
                 fun.data = "mean_cl_boot", geom = "bar", 
                 position=position_dodge(width=0.8), alpha=0.7)+
   stat_summary(aes(x=Metodo, y=Riqueza..S., group=Metodo, color=Metodo),
                 fun.data = "mean_cl_boot", geom = "errorbar", 
                 position=position_dodge(width=0.8))+
   geom_point(aes (x=Metodo, y=Riqueza..S., shape=Buzo, 
                   fill=Metodo), position = position_dodge(0.8))+
   #geom_jitter( aes (x=Metodo, y=Riqueza..S., shape=Buzo, 
  #                   fill=Metodo, group=Metodo))+
    scale_y_continuous(limits = c(0,6),
                      expand = c(0.01, 0.01),
                      breaks = seq(0, 6, 1),
                      name=expression("Riqueza de corales (S)"))

Coral_Richness 

Coral_Richness<-Coral_Richness +
  theme(legend.position="none",
        strip.background = element_blank(),
        strip.text.x = element_blank())

```

# 5. Time

## Model diving time

```{r}
Time_model_underwater<-lm(Minutos_campo ~  1 + Metodo + Buzo + Buzo*Metodo +
                          Zona + Sitio%in%Zona + 
                          Zona*Metodo + Zona*Buzo +
                          Zona*Metodo*Buzo + 
                          Sitio%in%Zona*Metodo +
                          Sitio%in%Zona*Buzo + 
                          Sitio%in%Zona*Metodo*Buzo,
                          data = Time.data)

 # summary(Time_model_underwater)                          
  anova(Time_model_underwater)
  par(mfrow=c(1,2))
  plot(Time_model_underwater)
  par(mfrow=c(1,1))
  
  Comp9<-emmeans(Time_model_underwater, ~Metodo)
  Comp9
  pairs(Comp9, adj="tukey")
  
  Comp10<-emmeans(Time_model_underwater, ~Metodo|Zona)
  pairs(Comp10, adj="tukey")
  
  Comp11<-emmeans(Time_model_underwater, ~Buzo|Metodo)
  pairs(Comp11, adj="tukey") 

```

## Model proccessing time

```{r}
Time_model_lab<-lm(Minutos_lab ~  1 + Metodo + Buzo + Buzo*Metodo +
                          Zona + Sitio%in%Zona + 
                          Zona*Metodo + Zona*Buzo +
                          Zona*Metodo*Buzo + 
                          Sitio%in%Zona*Metodo +
                          Sitio%in%Zona*Buzo + 
                          Sitio%in%Zona*Metodo*Buzo,
                          data = Time.data)

 # summary(Time_model_lab)                          
  anova(Time_model_lab)
  par(mfrow=c(1,2))
  plot(Time_model_lab)
  par(mfrow=c(1,1))
  
  Comp12<-emmeans(Time_model_lab, ~Metodo)
  Comp12
  pairs(Comp12, adj="tukey")
  
  Comp13<-emmeans(Time_model_lab, ~Metodo|Zona)
  pairs(Comp13, adj="tukey")
  
  Comp14<-emmeans(Time_model_lab, ~Buzo|Metodo)
  pairs(Comp14, adj="tukey") 

```

## Model total time

```{r}
Time_model<-lm(Tiempo.Total.1 ~  1 + Metodo + Buzo + Buzo*Metodo +
                          Zona + Sitio%in%Zona + 
                          Zona*Metodo + Zona*Buzo +
                          Zona*Metodo*Buzo + 
                          Sitio%in%Zona*Metodo +
                          Sitio%in%Zona*Buzo + 
                          Sitio%in%Zona*Metodo*Buzo,
                          data = Time.data)

 # summary(Time_model)                          
  anova(Time_model)
  par(mfrow=c(1,2))
  plot(Time_model)
  par(mfrow=c(1,1))
  
  Comp15<-emmeans(Time_model, ~Metodo)
  Comp15
  pairs(Comp15, adj="tukey")
  
  Comp16<-emmeans(Time_model, ~Metodo|Zona)
  pairs(Comp16, adj="tukey")
  
  Comp17<-emmeans(Time_model, ~Buzo|Metodo)
  pairs(Comp17, adj="tukey") 

```

## Plot

```{r}
Method_time<- ggplot(Time.data) +
  facet_grid(~Transecto)+
  MyTheme+ scale_shape_manual(values=c(21,22,25))+ 
  
  stat_summary(aes(x=Metodo, y=Tiempo.Total.1,
                 fill=Metodo, group=Metodo),
                 fun.data = "mean_cl_boot", geom = "bar",
                 position=position_dodge(width=0.8), alpha=0.5)+
  
   stat_summary(aes(x=Metodo, y=Minutos_campo,
                   fill=Metodo, group=Metodo),
                 fun.data = "mean_cl_boot", geom = "bar",
                 position=position_dodge(width=0.8), alpha=0.7)+
   stat_summary(aes(x=Metodo, y=Tiempo.Total.1,
                    group=Metodo, color=Metodo),
                 fun.data = "mean_cl_boot", geom = "errorbar",
                 position=position_dodge(width=0.8))+
  geom_point(aes (x=Metodo, y=Tiempo.Total.1, shape=Buzo, 
                   fill=Metodo), position = position_dodge(0.8))+
   #geom_jitter( aes (x=Metodo, y=Riqueza..S., shape=Buzo, 
  #                   fill=Metodo, group=Metodo))+
  
  scale_y_continuous(limits = c(0,60),
                      expand = c(0.01, 0.01),
                      breaks = seq(0, 60, 15),
                      name=expression("Tiempo (min) "))+
  theme(legend.position="none")
Method_time

Method_time<-Method_time+ facet_grid(~Transecto, switch = "both")
```

# Chapter figure 

```{r, echo=FALSE, fig.height=8, fig.width=8}
Figure<-ggarrange(Coral_Cover, Algae_Cover, Coral_Richness, Method_time,
          labels = c("A", "B", "C", "D"),
          ncol = 1, nrow = 4, heights=c(1.0, 0.8, .8, .8, 1.25))
Figure

#ggsave(file="Chapter_figure.svg", plot=Figure, dpi = 300, width=6.5, height=9)
```

# Model summary 
```{r}

library(modelsummary) # model results in table

Summary_models<-list("Corales (%)" = Coral_Cover_model, 
                       "Algas (%)" = Alga_Cover_model, 
                        "Riqueza (S)" = Richness_model_2, 
                         "Tiempo" = Time_model)
      
modelsummary(Summary_models, stars = TRUE, 
                   #statistic = c('std.error', 'p.value', 'conf.int'),
                   title = 'Seasonal and spatial models'#,
                   #coef_map=factor_order
                   )
```

# Packages used

```{r}
# Creates bibliography 
#knitr::write_bib(c(.packages()), "packages.bib")
```

